import { type Member } from "@/types/index"

export const dummyMembers: Member[] = [
  {
    id: "1",
    name: "Ahmad Fauzan",
    email: "ahmad.fauzan@student.unsri.ac.id",
    division: "Machine Learning",
    role: "Core Team",
    status: "Active",
    joinDate: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Siti Nurhaliza",
    email: "siti.nurhaliza@student.unsri.ac.id",
    division: "Front-End Development",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-02-20"),
  },
  {
    id: "3",
    name: "Budi Santoso",
    email: "budi.santoso@student.unsri.ac.id",
    division: "Back-End Development",
    role: "Executive",
    status: "Active",
    joinDate: new Date("2023-09-10"),
  },
  {
    id: "4",
    name: "Dewi Anggraini",
    email: "dewi.anggraini@student.unsri.ac.id",
    division: "UI/UX",
    role: "Core Team",
    status: "Active",
    joinDate: new Date("2024-01-05"),
  },
  {
    id: "5",
    name: "Rizki Pratama",
    email: "rizki.pratama@student.unsri.ac.id",
    division: "Cyber Security",
    role: "Member",
    status: "Non-Active",
    joinDate: new Date("2023-08-15"),
  },
  {
    id: "6",
    name: "Maya Putri",
    email: "maya.putri@student.unsri.ac.id",
    division: "Creative Design",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-03-01"),
  },
  {
    id: "7",
    name: "Andi Wijaya",
    email: "andi.wijaya@student.unsri.ac.id",
    division: "Mobile Development",
    role: "Core Team",
    status: "Active",
    joinDate: new Date("2023-11-20"),
  },
  {
    id: "8",
    name: "Fitri Rahayu",
    email: "fitri.rahayu@student.unsri.ac.id",
    division: "Public Relation",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-02-10"),
  },
  {
    id: "9",
    name: "Hendra Kusuma",
    email: "hendra.kusuma@student.unsri.ac.id",
    division: "Game Development",
    role: "Member",
    status: "Non-Active",
    joinDate: new Date("2023-07-25"),
  },
  {
    id: "10",
    name: "Linda Permata",
    email: "linda.permata@student.unsri.ac.id",
    division: "Videography",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-04-05"),
  },
];
