import { LeaderboardMember } from "@/types";

export const dummyLeaderboardMembers: LeaderboardMember[] = [
  {
    id: "1",
    name: "Ahmad Rizki",
    email: "ahmad@gdgoc.unsri.ac.id",
    division: "Machine Learning",
    role: "Core Team",
    status: "Active",
    joinDate: new Date("2024-01-15"),
    points: 150,
  },
  {
    id: "2",
    name: "Siti Nurhaliza",
    email: "siti@gdgoc.unsri.ac.id",
    division: "UI/UX",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-02-10"),
    points: 120,
  },
  {
    id: "3",
    name: "Budi Santoso",
    email: "budi@gdgoc.unsri.ac.id",
    division: "Back-End Development",
    role: "Executive",
    status: "Active",
    joinDate: new Date("2023-09-01"),
    points: 200,
  },
  {
    id: "4",
    name: "Dewi Lestari",
    email: "dewi@gdgoc.unsri.ac.id",
    division: "Front-End Development",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-03-05"),
    points: 85,
  },
  {
    id: "5",
    name: "Eko Prasetyo",
    email: "eko@gdgoc.unsri.ac.id",
    division: "Mobile Development",
    role: "Core Team",
    status: "Active",
    joinDate: new Date("2024-01-20"),
    points: 175,
  },
  {
    id: "6",
    name: "Fitri Handayani",
    email: "fitri@gdgoc.unsri.ac.id",
    division: "Cyber Security",
    role: "Member",
    status: "Non-Active",
    joinDate: new Date("2023-11-15"),
    points: 45,
  },
  {
    id: "7",
    name: "Gilang Ramadhan",
    email: "gilang@gdgoc.unsri.ac.id",
    division: "Game Development",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-02-28"),
    points: 95,
  },
  {
    id: "8",
    name: "Hana Pertiwi",
    email: "hana@gdgoc.unsri.ac.id",
    division: "Creative Design",
    role: "Core Team",
    status: "Active",
    joinDate: new Date("2024-01-08"),
    points: 160,
  },
  {
    id: "9",
    name: "Irfan Hakim",
    email: "irfan@gdgoc.unsri.ac.id",
    division: "Videography",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-04-01"),
    points: 70,
  },
  {
    id: "10",
    name: "Julia Rahmawati",
    email: "julia@gdgoc.unsri.ac.id",
    division: "Public Relation",
    role: "Member",
    status: "Active",
    joinDate: new Date("2024-03-15"),
    points: 110,
  },
];
